name: guilhermelange-desafio

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  app:
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    depends_on:
      - db
      
  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80